package main

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

type Group struct {
	GId        int64  `json:"g_id"`
	GName      string `json:"g_name"`
	TasksCount int64  `json:"tasks_count"`
}
