package main

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

type Task struct {
	TId       int64
	GId       int64
	TPriority int64
	TDate     string
	TSubject  string
	TComments string
}
