package main

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

type TasksDao struct {
	ds *DataStore
}

// (C)RUD: tasks
// Generated values are passed to DTO.

func (dao *TasksDao) CreateTask(p *Task) {
	sql := `insert into tasks (g_id, t_priority, t_date, t_subject, t_comments) values (?, ?, ?, ?, ?)`
	res := dao.ds.Insert(sql, "t_id", p.GId, p.TPriority, p.TDate, p.TSubject, p.TComments)
	dao.ds.Assign(&p.TId, res)
}

// C(R)UD: tasks

func (dao *TasksDao) ReadTask(tId int64) Task {
	sql := `select * from tasks where t_id=?`
	rd := dao.ds.QueryRow(sql, tId)
	obj := Task{}
	dao.ds.Assign(&obj.TId, rd["t_id"] /* t(t_id) <- t(t_id) */)
	dao.ds.Assign(&obj.GId, rd["g_id"] /* t(g_id) <- t(g_id) */)
	dao.ds.Assign(&obj.TPriority, rd["t_priority"] /* t(t_priority) <- t(t_priority) */)
	dao.ds.Assign(&obj.TDate, rd["t_date"] /* t(t_date) <- t(t_date) */)
	dao.ds.Assign(&obj.TSubject, rd["t_subject"] /* t(t_subject) <- t(t_subject) */)
	dao.ds.Assign(&obj.TComments, rd["t_comments"] /* t(t_comments) <- t(t_comments) */)
	return obj
}

// CR(U)D: tasks
// Returns the number of affected rows or -1 on error.

func (dao *TasksDao) UpdateTask(p *Task) int64 {
	sql := `update tasks set g_id=?, t_priority=?, t_date=?, t_subject=?, t_comments=? where t_id=?`
	return dao.ds.Exec(sql, p.GId, p.TPriority, p.TDate, p.TSubject, p.TComments, p.TId)
}

// CRU(D): tasks
// Returns the number of affected rows or -1 on error.

func (dao *TasksDao) DeleteTask(tId int64) int64 {
	sql := `delete from tasks where t_id=?`
	return dao.ds.Exec(sql, tId)
}

func (dao *TasksDao) GetGroupTasks(gId int64) []*Task {
	sql := `select * from tasks where g_id =? 
		order by t_id`
	var res []*Task
	onDto := func(rd map[string]interface{}) {
		obj := Task{}
		dao.ds.Assign(&obj.TId, rd["t_id"] /* t(t_id) <- q(t_id) */)
		dao.ds.Assign(&obj.GId, rd["g_id"] /* t(g_id) <- q(g_id) */)
		dao.ds.Assign(&obj.TPriority, rd["t_priority"] /* t(t_priority) <- q(t_priority) */)
		dao.ds.Assign(&obj.TDate, rd["t_date"] /* t(t_date) <- q(t_date) */)
		dao.ds.Assign(&obj.TSubject, rd["t_subject"] /* t(t_subject) <- q(t_subject) */)
		dao.ds.Assign(&obj.TComments, rd["t_comments"] /* t(t_comments) <- q(t_comments) */)
		res = append(res, &obj)
	}
	dao.ds.QueryAllRows(sql, onDto, gId)
	return res
}

// Returns the number of affected rows or -1 on error.

func (dao *TasksDao) DeleteGroupTasks(gId string) int64 {
	sql := `delete from tasks where g_id=?`
	return dao.ds.Exec(sql, gId)
}

func (dao *TasksDao) GetCount() int64 {
	sql := `select count(*) from tasks`
	r := dao.ds.Query(sql)
	var res int64
	dao.ds.Assign(&res, r)
	return res
}
